version: '3.8'

services:
  obt:
    container_name: obt
    image: ocfadmin/iotivity-examples
    tty: true
    stdin_open: true
    command: onboarding_tool
    networks:
      - ocfnet

  simpleserver:
    container_name: simpleserver
    image: ocfadmin/iotivity-examples
    tty: true
    stdin_open: true
    command: simpleserver
    networks:
      - ocfnet

  simpleclient:
    container_name: simpleclient
    image: ocfadmin/iotivity-examples
    tty: true
    stdin_open: true
    command: simpleclient
    networks:
      - ocfnet

# Note that IPv6 is not officially supported in compose file v3....
# IPv6 support must be enabled in /etc/docker/daemon.json
networks:
  ocfnet:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1
        - subnet: 2001:db8:2::/64
          gateway: 2001:db8:2::1
